### ISSUE TITLE
🍒 Low-hanging fruit

### ISSUE THREAD

**Issue by zgracem** [zachwick/homebrew-license#20]
I've collected licensing information (with URLs) for about 60 formulae in this gist: https://gist.github.com/zgracem/2605d22bd3608f47a38d961cc9ab7bb5

Someone with better git skills than me would probably find it trivial to automate an import from that file with `jq` and `hub`. (I tried to structure it for that purpose, but didn't feel confident enough to follow through.)

**Comment by zachwick** [comment]
Thank you so much for this great list @zgracem !! I've just merged a PR that puts all of these license strings into the canonical place, and please don't hesitate to do more of this kind of work. Happy hacking!
