### ISSUE TITLE
 Another batch of licenses

### ISSUE THREAD

**Issue by zgracem** [zachwick/homebrew-license#22]
I've collected another few dozen licenses in [this gist](https://gist.github.com/zgracem/3692c473c58bc53ba6e13ecbff104c77). There's a JSON file you can merge with the master `licenses.json` and a YAML file that includes URLs for reference.

This batch focuses on improving coverage for my personal <kbd>brew leaves</kbd> and the [top ~250 formulae](https://formulae.brew.sh/analytics/install-on-request/365d/) in general.

**Comment by zachwick** [comment]
@zgracem Thanks again for a great list of licensing information! I've added this information to the canonical place in #23 , and will be adding support for the "Public Domain (US)" license as well.
