### ISSUE TITLE
Add support for license info string "Public Domain (US)"

### ISSUE THREAD

**Issue by zachwick** [zachwick/homebrew-license#24]
Just like how there is support for the licensing info string "Custom", we should have support for "Public Domain (US)". This is not an SPDX identifier, but we should support it as the imagesnap project uses this license and is available via homebrew. This issue arose in #22 where licensing information for imagesnap was supplied, but caused the SPDX test to fail.

**Comment by MikeMcQuaid** [comment]
Worth a read on this: https://opensource.org/node/878

**Comment by zachwick** [comment]
This was already added in a previous commit, but the test script was not correctly checking for it.
