### ISSUE TITLE
Yet another batch of licenses

### ISSUE THREAD

**Issue by zgracem** [zachwick/homebrew-license#25]
Following on from #20 and #22, here is [another gist of licenses](https://gist.github.com/zgracem/0726803b4ab0c6cb245caf31426308a7) in "canonical" JSON format, plus a YAML file w/ URLs.

(Where URLs are missing in the YAML file, licensing info was either self-evident—e.g. Apache projects—or extracted from a downloaded sourceball because I couldn't find a copy online.)

This completes licensing info for nearly all of the [top 250 installed-by-request formulae](https://formulae.brew.sh/analytics/install-on-request/365d/).

**Comment by zachwick** [comment]
@zgracem These have been a huge help, and I'm very thankful for all of your efforts here tracking down licensing information for all of these formulae.

**Comment by zgracem** [comment]
Very happy to help! :tada:
