### ISSUE TITLE
How to contribute with licenses?

### ISSUE THREAD

**Issue by ondrejfuhrer** [zachwick/homebrew-license#5]
Hello @zachwick 

When doing the PR I was actually wondering, how we, as a community, should contribute. If a lot of people start making PR for "random" formulas, I totally can see a "conflict hell" happening in the merging process. 

I think it would be great to mention that the contribution section of the readme, i.e. 1 PR = 1 License change, therefore you won't have multiple PR conflicting. What do you think about it?

**Comment by zachwick** [comment]
== I'll add something to the README specifically about contributing licensing information, and will set up some issue/PR templates for each of bug, feature request, licensing information type requests.

**Comment by zachwick** [comment]
I think with https://github.com/zachwick/homebrew-license/commit/82d85ae51927b73d39ec309d633d2beee608ecfc and the issue reporting template, this is now good enough until we run into another variety of contribution issues.
